name: 'Gradle Action'
description: 'Run Gradle tasks'
inputs:
  tasks:
    description: 'gradle tasks to run (space separated)'
    required: true
  googleServices:
    description: 'google-services config file'
    required: true
  sonarBaseUrl:
    description: 'Sonar base url'
    required: true
  sonarHeaderValue:
    description: 'Sonar header value'
    required: true
  pactBrokerUrl:
    description: 'URL of pact broker'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_TASKS: ${{ inputs.tasks }}
    INPUT_GOOGLE_SERVICES: ${{ inputs.googleServices }}
    INPUT_SONAR_BASE_URL: ${{ inputs.sonarBaseUrl }}
    INPUT_SONAR_HEADER_VALUE: ${{ inputs.sonarHeaderValue }}
    INPUT_PACTBROKER_URL: ${{ inputs.pactBrokerUrl }}
