name: 'Run instrumentation tests'
description: 'Setup GCloud CLI'
inputs:
  googleCloudServiceAccount:
    description: 'Google Cloud Service Account'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GOOGLE_CLOUD_SERVICE_ACCOUNT: ${{ inputs.googleCloudServiceAccount }}
