name: generate-release-note

on:
  repository_dispatch:
    types: [generate-release-note]

jobs:
  generate-release-note:
    runs-on:
      - self-hosted
      - linux
      - aws
    steps:
      - name: Checkout ci tools
        id: checkout-ci-tools
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          persist-credentials: false
          repository: nhsx/sonar-ios # This will be extracted to separate repo when available
          path: ci-tools
          ref: df8714dd
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
