name: CI

on:
  push:
    branches:
      - master
      - ci
      - 'releases/**'

jobs:

  build:
    runs-on:
      - self-hosted
      - linux
      - aws

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle Distribution
        uses: actions/cache@v2
        with:
          path: /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build & Test
        uses: ./.github/actions/build-action
        with:
          googleServices: ${{ secrets.GoogleServices }}
          sonarBaseUrl: ${{ secrets.TestSonarBaseUrl }}
          sonarHeaderValue: ${{ secrets.TestSonarHeaderValue }}
          sonarAnalyticsKey: ${{ secrets.TestSonarAnalyticsKey }}
          pactBrokerUrl: https://sonar-pact-broker-app.apps.nonprod.aws.cp.data.england.nhs.uk

      - name: Upload pacts
        uses: actions/upload-artifact@v2
        with:
          name: pacts-${{ github.sha }}
          path: app/pacts

      - name: Instrumented Test
        uses: ./.github/actions/instrumentation-action
        with:
          googleCloudServiceAccount: ${{ secrets.ServiceAccount }}

      - name: Notify Slack on Failure
        if: ${{ github.ref == 'refs/heads/master' && failure() }}
        uses: rtCamp/action-slack-notify@96d5e2a64fc78a6b7ac13265f55bee296869967a
        env:
          SLACK_WEBHOOK: ${{ secrets.SonarAndroidWebHook }}
          SLACK_COLOR: '#FF0000'
          SLACK_USERNAME: CI
          SLACK_TITLE: Commit Message
