name: CI

on:
  push:
    branches:
      - master

jobs:

  pull_docker_image:
    runs-on:
      - self-hosted
      - linux
      - aws
    steps:
      - name: Login to Docker
        run: |
          docker login -u "${{secrets.docker_username}}" \
          -p "${{secrets.docker_password}}" \
          "nhsxpivotal.azurecr.io"
      - name: Pull Image
        run: |
          docker pull nhsxpivotal.azurecr.io/sonar-colocate-services-image

  build:
    needs: pull_docker_image
    runs-on:
      - self-hosted
      - linux
      - aws
    container: nhsxpivotal.azurecr.io/sonar-colocate-services-image

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and test
        uses: ./.github/actions/build-action
        env:
          GOOGLE_SERVICES: ${{ secrets.GoogleServices }}
          TEST_SONAR_HEADER_VALUE: ${{ secrets.TestSonarHeaderValue }}

      - name: Instrumentation test
        uses: ./.github/actions/instrumentation-action
        env:
          SERVICE_ACCOUNT: ${{ secrets.ServiceAccount }}

      - name: Publish
        uses: ./.github/actions/publish-action
        env:
          BUILD_FLAVOR: Staging
          PLAY_TRACK: internal
          GOOGLE_SERVICES: ${{ secrets.GoogleServices }}
          PLAY_SERVICES: ${{ secrets.PlayServices }}
          SIGNING_KEY_STORE: ${{ secrets.signingKeyStore }}
          SIGNING_KEY_ALIAS: ${{ secrets.signingKeyStoreAlias }}
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.signingKeyStorePassword }}
          SIGNING_KEY_PASSWORD: ${{ secrets.signingKeyPassword }}
          SONAR_HEADER_VALUE: ${{ secrets.TestSonarHeaderValue }}
          SONAR_ANALYTICS_KEY: ${{ secrets.TestSonarAnalyticsKey }}
          SONAR_BASE_URL: https://test.route.cp.data.england.nhs.uk
          COMMIT_SHA: ${{ github.sha }}
