name: CI

on:
  push:
    branches:
      - master
      - ci

jobs:

  build:
    runs-on:
      - self-hosted
      - linux
      - aws
      - blue

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle Packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build & Test
        uses: ./.github/actions/build-action
        with:
          googleServices: ${{ secrets.GoogleServices }}
          sonarHeaderValue: ${{ secrets.TestSonarHeaderValue }}
          sonarAnalyticsKey: ${{ secrets.TestSonarAnalyticsKey }}

      - name: Instrumented Test
        uses: ./.github/actions/instrumentation-action
        with:
          googleCloudServiceAccount: ${{ secrets.ServiceAccount }}

      - name: Notify Slack on Failure
        if: ${{ github.ref == 'refs/heads/master' && failure() }}
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SonarAndroidWebHook }}
          SLACK_COLOR: '#FFBF00'
          SLACK_USERNAME: CI
          SLACK_TITLE: Commit Message
