# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  login_to_docker:
    runs-on:
      - linux
      - self-hosted
    steps:
      - name: Login to Docker
        run: |
          docker login -u "${{secrets.docker_username}}" \
          -p "${{secrets.docker_password}}" \
          "nhsxpivotal.azurecr.io"
      - name: Pull Image
        run: |
          docker pull nhsxpivotal.azurecr.io/sonar-colocate-services-image

  build:
    # The type of runner that the job will run on
    needs: login_to_docker
    runs-on: [ "self-hosted", "linux" ]
    container: nhsxpivotal.azurecr.io/sonar-colocate-services-image

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and test
        uses: ./.github/actions/build-action
        env:
          SERVICE_ACCOUNT: ${{ secrets.ServiceAccount }}
          GOOGLE_SERVICES: ${{ secrets.GoogleServices }}

  publish:
    needs: build
    runs-on: [ "self-hosted", "linux" ]
    container: nhsxpivotal.azurecr.io/sonar-colocate-services-image

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Publish
        uses: ./.github/actions/publish-action
        env:
          FIREBASE_SERVICES: ${{ secrets.GoogleServices }}
          PLAY_SERVICES: ${{ secrets.PlayServices }}
          SIGNING_KEY_STORE: ${{ secrets.signingKeyStore}}
          SIGNING_KEY_ALIAS: ${{ secrets.signingKeyStoreAlias}}
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.signingKeyStorePassword}}
          SIGNING_KEY_PASSWORD: ${{ secrets.signingKeyPassword}}

