name: CI

on:
  push:
    branches:
      - master
      - ci

jobs:

  build:
    runs-on:
      - self-hosted
      - linux
      - aws

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and test
        uses: ./.github/actions/build-action
        env:
          GOOGLE_SERVICES: ${{ secrets.GoogleServices }}
          TEST_SONAR_HEADER_VALUE: ${{ secrets.TestSonarHeaderValue }}
          SONAR_ANALYTICS_KEY: ${{ secrets.TestSonarAnalyticsKey }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Instrumentation test
        uses: ./.github/actions/instrumentation-action
        env:
          SERVICE_ACCOUNT: ${{ secrets.ServiceAccount }}

      - name: Notify Slack on Failure
        if: ${{ github.ref == 'refs/heads/master' && failure() }}
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SonarAndroidWebHook }}
          SLACK_COLOR: '#FFBF00'
          SLACK_USERNAME: CI
          SLACK_TITLE: Commit Message
