name: Tag a version as supported

on:
  push:
    branches:
      - master

jobs:
  checkout:
    outputs:
      shortref: ${{ steps.commitsha.outputs.short }}
    runs-on:
      - self-hosted
      - linux
      - aws
      - blue

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Get Commit Hash
        id: commitsha
        run: |
          echo ::set-output name=short::$(git rev-parse --short HEAD)
          echo ::set-output name=long::$(git rev-parse HEAD)

  tag:
    runs-on:
      - self-hosted
      - linux
      - aws
      - blue

    needs: checkout
    container: pactfoundation/pact-cli

    steps:
      - name: Tag version as supported in pact broker
        run: pact-broker create-version-tag --tag supported --pacticipant 'Android App' --version ${{ needs.checkout.outputs.shortref }}
        env:
          PACT_BROKER_URL: https://sonar-pact-broker-app.apps.nonprod.aws.cp.data.england.nhs.uk
