name: Publish Internal

on:
  repository_dispatch:
    types: [publish-internal]

jobs:

  publish:
    runs-on:
      - self-hosted
      - linux
      - aws

    outputs:
      build-number: ${{ steps.publish.outputs.buildVersion }}
      tag: ${{ steps.tag-commit.outputs.tag }}
      previous-tag: ${{ steps.tag-commit.outputs.previous-tag }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Get Commit Short Hash
        id: commitsha
        run: echo ::set-output name=short::$(git rev-parse --short HEAD)

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Publish Internal
        id: publish
        uses: ./.github/actions/publish-action
        with:
          buildFlavor: Internal
          playTrack: internal
          googleServices: ${{ secrets.GoogleServices }}
          playServices: ${{ secrets.PlayServices }}
          signingKeyStore: ${{ secrets.signingKeyStore }}
          signingKeyStoreAlias: ${{ secrets.signingKeyStoreAlias }}
          signingKeyStorePassword: ${{ secrets.signingKeyStorePassword }}
          signingKeyPassword: ${{ secrets.signingKeyPassword }}
          sonarHeaderValue: ${{ secrets.TestSonarHeaderValue }}
          sonarAnalyticsKey: ${{ secrets.TestSonarAnalyticsKey }}
          sonarBaseUrl: ${{ secrets.TestSonarBaseUrl }}
          sonarUrlApplyCoronavirusTest: https://self-referral.test-for-coronavirus.service.gov.uk/cta-start
          commitSha: ${{ steps.commitsha.outputs.short }}

      - name: Upload Internal APK
        uses: actions/upload-artifact@v2
        with:
          name: app-internal-${{ steps.publish.outputs.buildVersion }}(${{ steps.commitsha.outputs.short }}).apk
          path: app/build/outputs/apk/internal/app-internal.apk

      - name: Upload Internal AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-internal-${{ steps.publish.outputs.buildVersion }}(${{ steps.commitsha.outputs.short }}).aab
          path: app/build/outputs/bundle/internal/app-internal.aab

      - name: Tag Commit
        id: tag-commit
        run: |
          previous_tag=$(git tag --list | grep "internal" | tail -n 1)
          echo "::set-output name=previous-tag::$previous_tag"

          tag=internal-${{ steps.publish.outputs.buildVersion }}
          git tag ${tag}
          git push origin ${tag}
          echo "::set-output name=tag::${tag}"

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@96d5e2a64fc78a6b7ac13265f55bee296869967a
        env:
          SLACK_WEBHOOK: ${{ secrets.SonarAndroidWebHook }}
          SLACK_COLOR: '#138275'
          SLACK_USERNAME: CI
          SLACK_TITLE: New Internal Release
          SLACK_MESSAGE: |
            - Internal Build: ${{ steps.publish.outputs.buildVersion }}(${{ steps.commitsha.outputs.short }})
            - APK and AAB are uploaded as job artefacts

  update-pivotal-tracker-backlog:
    runs-on:
    - linux
    - self-hosted
    - aws
    needs: publish
    steps:
      - name: Checkout Android Project
        uses: actions/checkout@01aeccc # v2.1.0
        with:
          fetch-depth: 0

      - name: Checkout Sonar CI Github Repo
        uses: actions/checkout@01aeccc #v2.1.0
        with:
          token: ${{ secrets.deployment_token }}
          repository: nhsx/sonar-ci-tools
          path: ci-tools
          ref: v0.2.0

      - name: Update Backlog
        uses: ./ci-tools/.github/actions/deliver_tracker_stories_with_build
        with:
          tracker_token: ${{ secrets.tracker_api_token }}
          revision_range: ${{ needs.publish.outputs.previous-tag }}..${{ needs.publish.outputs.tag }}
          build_version: ${{ needs.publish.outputs.build-number }}

