name: Publish Internal

on:
  repository_dispatch:
    types: [publish-internal]

jobs:

  publish:
    runs-on:
      - self-hosted
      - linux
      - aws

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ::set-output name=commitsha::$(git rev-parse --short HEAD)

      - name: Cache Gradle Packages
        uses: actions/cache@v1
        with:
          path: /root/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Publish Internal
        id: publish
        uses: ./.github/actions/publish-action
        with:
          buildFlavor: Internal
          playTrack: internal
          googleServices: ${{ secrets.GoogleServices }}
          playServices: ${{ secrets.PlayServices }}
          signingKeyStore: ${{ secrets.signingKeyStore }}
          signingKeyStoreAlias: ${{ secrets.signingKeyStoreAlias }}
          signingKeyStorePassword: ${{ secrets.signingKeyStorePassword }}
          signingKeyPassword: ${{ secrets.signingKeyPassword }}
          sonarHeaderValue: ${{ secrets.TestSonarHeaderValue }}
          sonarAnalyticsKey: ${{ secrets.TestSonarAnalyticsKey }}
          sonarBaseUrl: ${{ secrets.TestSonarBaseUrl }}
          commitSha: ${{ github.event.client_payload.ref }}

      - name: Upload Internal APK
        uses: actions/upload-artifact@v2
        with:
          name: app-internal-${{ steps.publish.outputs.buildVersion }}($${ github.event.client_payload.ref }}).apk
          path: app/build/outputs/apk/internal/app-internal.apk

      - name: Upload Internal AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-internal-${{ steps.publish.outputs.buildVersion }}($${ github.event.client_payload.ref }}).aab
          path: app/build/outputs/bundle/internal/app-internal.aab

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SonarAndroidWebHook }}
          SLACK_COLOR: '#138275'
          SLACK_USERNAME: CI
          SLACK_TITLE: New Internal Release
          SLACK_MESSAGE: |
            - Internal Build: ${{ steps.publish.outputs.buildVersion }}($${ github.event.client_payload.ref }})
            - APK and AAB are uploaded as job artefacts
